INFO:src.fighting_env:Waiting for frontend connection...
INFO:src.webrtc_client:Shutting down WebRTC client...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/d/progress/AI_Battle_Arena/src/webrtc_client.py", line 38, in run
    self.loop.run_until_complete(self.connect(backend_peer_id))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/mnt/d/progress/AI_Battle_Arena/src/webrtc_client.py", line 68, in connect
    self.peer = Peer(backend_peer_id, host=PEERJS_HOST, port=PEERJS_PORT, path=PEERJS_PATH)
  File "/mnt/d/progress/AI_Battle_Arena/venv/lib/python3.9/site-packages/peerpy/peer.py", line 28, in __init__
    self.server.bind((address, int(port)))
socket.gaierror: [Errno -3] Temporary failure in name resolution
